homepage:
  path: /
  controller: App\Controller\BlogController::recherche

article_add:
  path: /add
  controller: App\Controller\BlogController::add

article_show:
  path: /show/{id}
  controller: App\Controller\BlogController::show

article_edit:
  path: /edit/{id}
  controller: App\Controller\BlogController::edit
  requirements:
    id: '\d+'

article_remove:
  path: /remove/{id}
  controller: App\Controller\BlogController::remove
  requirements:
    id: '\d+'

admin:
  path: /admin
  controller: App\Controller\BlogController::admin

admin_user_delete:
  path: /admin/user_delete/{id}
  controller: App\Controller\BlogController::admin_user_delete

user_account:
  path: /user/account/{id}
  controller: App\Controller\blogController::user_account

